### ISSUE TITLE
TH header text hide sort arrow

### ISSUE THREAD

**Issue by BuhtigithuB** [DataTables/Plugins#165] opened 2015-02-24 20:08 UTC
Hello,

I submit a PR : https://github.com/DataTables/Plugins/pull/148/commits

Solving at least for me the issue... I don't know why it wasn't merge.

But I still experiment the issue with Plugins 1.10.5 bootstrap 2.

The TH header text overlay DTs sort arrow.

Thanks to reconsider this PR or find another solution.

Patch manually the same file with the same CSS works under 1.10.5 plugins extension.

Richard

**Comment by DataTables** [comment] 2015-02-24 21:48
I didn't review the other PR as you closed it shortly after opening it. 

Can you please link to a test case showing the issue that you are having.

**Comment by BuhtigithuB** [comment] 2015-02-25 18:03
Ok, I may have made a mistake, I will try to investigate this.

I try to join a screenshot
without fix
![without_css](https://cloud.githubusercontent.com/assets/1660615/6376893/b004bc70-bcee-11e4-9f07-e6018ec59911.png)
with fix
![with_css](https://cloud.githubusercontent.com/assets/1660615/6376898/b6a06a70-bcee-11e4-9c1b-815b1a290eca.png)

**Comment by BuhtigithuB** [comment] 2015-02-25 18:14
Here it is : https://github.com/DataTables/Plugins/pull/167

**Comment by DataTables** [comment] 2015-04-02 13:42
Sorry for the delay in looking into this. it looks like you are including the DataTables default stylesheet on a page where you are also including the Bootstrap integration stylesheet (although without a test case it is hard to be sure).

You should include only the Bootstrap integration stylesheet if you are using bootstrap. I'm unable to reproduce this problem with just the last Bootstrap integration stylesheet from the repo.

**Closed by DataTables** 2015-04-02 13:42 UTC
