### ISSUE TITLE
There is a Dist repo for font-awesome plugin?

### ISSUE THREAD

**Issue by klarkc** [DataTables/Plugins#247] opened 2016-02-02 12:57 UTC
Hello, seems to be missing a distribution repository for this integration plugin. I am trying to use the datatables.net bower repositories and I can't find a repository for this plugin.

**Comment by DataTables** [comment] 2016-02-02 13:00
See #224. Closing as a duplicate of that thread.

**Closed by DataTables** 2016-02-02 13:00 UTC
