### ISSUE TITLE
Ellipsis plugin issues

### ISSUE THREAD

**Issue by lenamtl** [DataTables/Plugins#337] opened 2017-05-30 15:55 UTC
When using ellipsis https://datatables.net/plug-ins/dataRender/ellipsis

I'm having a few issues and cannot use it :

When print or exporting we can see this code appearing instead of the content of the column
```
<span class="ellipsis" title="Lorem Ipsum is simply dummy text of the
versions of Lorem Ipsum. ">Lorem Ipsum is simply dummy…
```

When using with colvis, colreorder and responsive
on small view if I change the column order the content is no more visible because the span get duplicated like this
`<span class="dtr-data"><span class="ellipsis" title="<span class=&quot;ellipsis&quot; title=&quot;Verylongtaskmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw&quot;>Verylongtaskmmmmmmmmmmmmmmmmm…</span>"><span class="ellipsis" &#8230;<="" span=""></span></span></span>`

I have opened a post about it last year and still no fix for this
https://datatables.net/forums/discussion/39311

I'd like to be able to use it but there are too many bugs.

Thanks

**Comment by DataTables** [comment] 2017-08-16 11:34
I'm sorry for such a long delay in replying here. Embarrassingly long! Its been sitting in my inbox and I'm only just getting to it now...

The first issue with the export is being caused by the fact that Buttons will export the rendered data by default (i.e. what you see in the table, is what is exported). You can control this through the `exportOptions.orthogonal` option. Here is a little example: http://live.datatables.net/borifara/1/edit . Setting the value to be `null` means "use the original data". `display` is the default value.

I'm not seeing the duplicate tag issue with Responsive though: http://live.datatables.net/lakixeji/1/edit . It is possible that was a bug with an older version of Responsive perhaps?

**Comment by lenamtl** [comment] 2017-08-17 15:21
Thanks I didn't know about exportOptions.orthogonal

The duplicated span problem occurred 
when using ellipsis with colvis, colreorder and responsive
to reproduce
you need to be in small view / mobile view
change the column order, you will see the content is no more visible because the span get duplicated like this
`<span class="dtr-data"><span class="ellipsis" title="<span class=&quot;ellipsis&quot; title=&quot;Verylongtaskmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw&quot;>Verylongtaskmmmmmmmmmmmmmmmmm…</span>"><span class="ellipsis" &#8230;<="" span=""></span></span></span>`

**Comment by DataTables** [comment] 2017-08-25 10:17
This one is a bit trickier. What is happening is that _ColReorder_ is invalidating the data in the columns that have changed, and thus it is reading in the ellipsis value as the new value, since that is what is displayed in the column. That is a more general bug in ColReorder than just the ellipsis plug-in.

**Comment by AllanJard** [comment] 2023-12-20 11:15
I've rewritten ColReorder and v2 will be released soon (January sometime) which will address this issue.

**Closed by AllanJard** 2023-12-20 11:15 UTC
